[disable-ruff.lua]
pos=@Point(12 528)

[libreoffice-qt6.desktop]
pos=@Point(292 12)

[org.kde.elisa.desktop]
pos=@Point(12 399)

[qterminal.desktop]
pos=@Point(152 12)

[user-home.desktop]
pos=@Point(12 141)
