# 使用 Maple Mono 字体（绝对路径）
# font_family      /data/data/com.termux/files/home/.local/share/fonts/MapleMono.ttf
# bold_font        /data/data/com.termux/files/home/.local/share/fonts/MapleMono.ttf
# italic_font      /data/data/com.termux/files/home/.local/share/fonts/MapleMono.ttf
# bold_italic_font /data/data/com.termux/files/home/.local/share/fonts/MapleMono.ttf

# 设置字体大小
font_size 11


# BEGIN_KITTY_FONTS
font_family      family="Maple Mono NF CN"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
#################################### HIGHLIGHT #################################
mark1_foreground #74c7ec
mark1_background #1E1E2E
mark2_foreground #F9E2AF
mark2_background #1E1E2E
mark3_foreground #F38BA8
mark3_background #1E1E2E
toggle_marker regex 1 \\bINFO\\b 2 \\bWARNING\\b 3 \\bERROR\\b 3 \\bFATAL\\b
map ctrl+shift+m toggle_marker regex 1 \\bINFO\\b 2 \\bWARNING\\b 3 \\bERROR\\b 3 \\bFATAL\\b

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include theme.conf
# END_KITTY_THEME
#################################### CURSOR ####################################
cursor_shape block
cursor_trail 300
cursor_trail_start_threshold 60
cursor_trail_decay 0.15 0.45
cursor_blink_interval 0
detect_urls no
mouse_hide_wait 0.5
# 光标颜色（Catppuccin Mocha 紫色）
cursor           #cba6f7

# 光标下文字的颜色
cursor_text_color #1e1e2e

# 光标闪烁间隔（秒）。设为 0 禁用闪烁，负值使用系统默认
cursor_blink_interval     0.5

# 停止闪烁的闲置时间（秒）。设为 0 或负值则永不停止
cursor_stop_blinking_after 0
