[General]
__userfile__=true
iconTheme=

[desktopswitch]
alignment=Left

[fancymenu]
icon=/usr/share/lxqt/themes/catppuccin-mocha/penguin.png
ownIcon=true

[mount]
alignment=Right

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\x1\xff\xff\xcb\xcb\xa6\xa6\xfe\xfe\0\0)
hidable=false
hide-on-overlap=false
iconSize=22
lineCount=1
lockPanel=false
opacity=100
panelSize=32
plugins=fancymenu, desktopswitch, quicklaunch, taskbar, statusnotifier, tray, mount, volume, worldclock
position=Bottom
reserve-space=true
show-delay=0
visible-margin=true
width=100
width-percent=true

[quicklaunch]
apps\1\desktop=/home/flt18355/Desktop/org.kde.konsole.desktop
apps\2\desktop=/usr/share/applications/org.flameshot.Flameshot.desktop
apps\3\desktop=/home/flt18355/Desktop/Chromium.desktop
apps\4\desktop=/home/flt18355/Desktop/obsidian.desktop
apps\5\desktop=/home/flt18355/Desktop/octopi.desktop
apps\6\desktop=/home/flt18355/Desktop/audacious.desktop
apps\size=6

[taskbar]
alignment=Left

[tray]
alignment=Right

[volume]
alignment=Right

[worldclock]
alignment=Right
autoRotate=true
customFormat="'<b>'HH:mm:ss'</b><br/><font size=\"-2\">'ddd, d MMM yyyy'<br/>'TT'</font>'"
dateFormatType=custom
dateLongNames=false
datePadDay=false
datePosition=below
dateShowDoW=false
dateShowYear=false
defaultTimeZone=Asia/Shanghai
formatType=custom-timeonly
showDate=false
showTimezone=false
showTooltip=false
showWeekNumber=true
timeAMPM=true
timePadHour=true
timeShowSeconds=true
timeZoneWheel=true
timeZones\1\customName=
timeZones\1\timeZone=Asia/Shanghai
timeZones\size=1
timezoneFormatType=iana
timezonePosition=below
useAdvancedManualFormat=false
