# [可选] 选择主题配色，改成你喜欢的就好，默认为 'mocha'
set -g @catppuccin_flavor 'mocha' # 可选值: latte, frappe, macchiato, mocha

set -g @catppuccin_status_modules_right "session application date_time"
set -g status-right "#{E:@catppuccin_status_session}#{E:@catppuccin_status_application}#{E:@catppuccin_status_date_time}"

# 列出你想要使用的插件（这里就是 Catppuccin 主题）
set -g @plugin 'catppuccin/tmux'

# 初始化 TPM 插件管理器，这行必须放在所有 `set -g @plugin` 命令的后面
run '~/.tmux/plugins/tpm/tpm'

set -g default-terminal "tmux-256color"
