[General]
__theme_updated__=1780700692994
__userfile__=true
icon_follow_color_scheme=false
icon_theme=Catppuccin-Mocha-Alt2
theme=catppuccin-mocha
tool_bar_icon_size=24
wallpaper_override=true

[Palette]
base_color=#ffffff
highlight_color=#3c8ce6
highlighted_text_color=#ffffff
link_color=#0000ff
link_visited_color=#ff00ff
text_color=#000000
tooltip_base_color=#ffffdc
tooltip_text_color=#000000
window_color=#efefef
window_text_color=#000000

[Qt]
font="Maple Mono NF CN,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
style=kvantum
