[General]
AllowGrabBaseKeypad=true
AllowGrabBaseSpecial=false
AllowGrabLocks=false
AllowGrabMiscKeypad=true
AllowGrabMiscSpecial=true
MultipleActionsBehaviour=first
WindowSize=@Invalid()

[Alt%2BF1.1]
Comment=显示/隐藏主菜单
Enabled=true
path=/panel/fancymenu/show_hide

[Alt%2BF2.2]
Comment=显示/隐藏对话框
Enabled=true
path=/runner/show_hide_dialog

[Control%2BAlt%2BD.3]
Comment=显示桌面
Enabled=true
path=/panel/showdesktop/show_hide

[Control%2BAlt%2BE.4]
Comment=PCManFM-Qt
Enabled=true
Exec=pcmanfm-qt

[Control%2BAlt%2BI.5]
Comment=Web Browser
Enabled=true
Exec=xdg-open, about:blank

[Control%2BAlt%2BL.6]
Comment=Lockscreen
Enabled=true
Exec=xdg-screensaver, lock

[Control%2BAlt%2BT.7]
Comment=QTerminal
Enabled=true
Exec=qterminal

[Control%2BF1.8]
Comment=切换至桌面 1
Enabled=true
path=/panel/desktopswitch/desktop_1

[Control%2BF10.9]
Comment=切换至桌面 10
Enabled=true
path=/panel/desktopswitch/desktop_10

[Control%2BF11.10]
Comment=切换至桌面 11
Enabled=true
path=/panel/desktopswitch/desktop_11

[Control%2BF12.11]
Comment=切换至桌面 12
Enabled=true
path=/panel/desktopswitch/desktop_12

[Control%2BF2.12]
Comment=切换至桌面 2
Enabled=true
path=/panel/desktopswitch/desktop_2

[Control%2BF3.13]
Comment=切换至桌面 3
Enabled=true
path=/panel/desktopswitch/desktop_3

[Control%2BF4.14]
Comment=切换至桌面 4
Enabled=true
path=/panel/desktopswitch/desktop_4

[Control%2BF5.15]
Comment=切换至桌面 5
Enabled=true
path=/panel/desktopswitch/desktop_5

[Control%2BF6.16]
Comment=切换至桌面 6
Enabled=true
path=/panel/desktopswitch/desktop_6

[Control%2BF7.17]
Comment=切换至桌面 7
Enabled=true
path=/panel/desktopswitch/desktop_7

[Control%2BF8.18]
Comment=切换至桌面 8
Enabled=true
path=/panel/desktopswitch/desktop_8

[Control%2BF9.19]
Comment=切换至桌面 9
Enabled=true
path=/panel/desktopswitch/desktop_9

[Meta%2B0.20]
Comment=激活任务 10
Enabled=true
path=/panel/taskbar/task_10

[Meta%2B1.21]
Comment=激活任务 1
Enabled=true
path=/panel/taskbar/task_1

[Meta%2B2.22]
Comment=激活任务 2
Enabled=true
path=/panel/taskbar/task_2

[Meta%2B3.23]
Comment=激活任务 3
Enabled=true
path=/panel/taskbar/task_3

[Meta%2B4.24]
Comment=激活任务 4
Enabled=true
path=/panel/taskbar/task_4

[Meta%2B5.25]
Comment=激活任务 5
Enabled=true
path=/panel/taskbar/task_5

[Meta%2B6.26]
Comment=激活任务 6
Enabled=true
path=/panel/taskbar/task_6

[Meta%2B7.27]
Comment=激活任务 7
Enabled=true
path=/panel/taskbar/task_7

[Meta%2B8.28]
Comment=激活任务 8
Enabled=true
path=/panel/taskbar/task_8

[Meta%2B9.29]
Comment=激活任务 9
Enabled=true
path=/panel/taskbar/task_9

[Print.30]
Comment=Screenshot
Enabled=true
Exec=screengrab, -f

[Shift%2BControl%2BF6.31]
Comment=☀ ↓
Enabled=true
Exec=lxqt-config-brightness, -d

[Shift%2BControl%2BF7.32]
Comment=☀ ↑
Enabled=true
Exec=lxqt-config-brightness, -i

[XF86AudioLowerVolume.33]
Comment=减小音量
Enabled=true
path=/panel/volume/down

[XF86AudioMute.34]
Comment=静音/取消静音
Enabled=true
path=/panel/volume/mute

[XF86AudioRaiseVolume.35]
Comment=增大音量
Enabled=true
path=/panel/volume/up

[XF86Display.36]
Comment=Launch Monitor
Enabled=true
Exec=lxqt-config-monitor

[XF86Eject.37]
Comment=弹出可移动媒体
Enabled=true
path=/panel/mount/eject

[XF86MonBrightnessDown.38]
Comment=☀ ↓
Enabled=true
Exec=lxqt-config-brightness, -d

[XF86MonBrightnessUp.39]
Comment=☀ ↑
Enabled=true
Exec=lxqt-config-brightness, -i

[XF86PowerOff.40]
Comment=关闭电源按键操作
Enabled=true
path=/powermanager/keypoweroff

[XF86Sleep.41]
Comment=休眠的按键操作
Enabled=true
path=/powermanager/keyhibernate

[XF86Suspend.42]
Comment=暂停的按键操作
Enabled=true
path=/powermanager/keysuspend
